### ISSUE TITLE
Latency in fetching from db 

### ISSUE THREAD

**Issue by adamdab** [IO2-team-3/backend#19]
We have expirienced latency in fetching from db during our demo
Steps to do:
- test with better internet connection
- test if it is issue with BE or FE

**Comment by adamdab** [comment]
need to confirm form FE [@DybowskiB  @Agat2oo1] and Mobile [@AleksyBalazinski] team : https://github.com/IO2-team-3/backend/pull/23

**Comment by AleksyBalazinski** [comment]
mobile: fetching list of events takes approx. 8 seconds and getting events by category takes approx. 6 seconds. What about FE?

**Comment by adamdab** [comment]
> mobile: fetching list of events takes approx. 8 seconds and getting events by category takes approx. 6 seconds. What about FE?

I see that we are still using fetchAll() and then find in them events with wanted category, I will fix this to be something like findBy Category()
